# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"                     # contains requirements.txt
    schedule:
      interval: "weekly"               # daily | weekly | monthly
      day: "monday"
      time: "09:00"
      timezone: "America/Indiana/Indianapolis"
    open-pull-requests-limit: 5
    labels: ["dependencies", "automated"]
    commit-message:
      prefix: "deps"
      include: "scope"
