name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEFAULT_USER: ${{ secrets.DEFAULT_USER }}
      DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LOG_LEVEL: 2
      AWS_CONFIG_FILE: .aws/config
    steps:
      # Backend (Python) tests
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backend tests
        run: pytest --capture=sys -v

      
      # Frontend Setup + E2E tests
      - name: Setup Node.js 20 for frontend
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      # Start backend API server in background
      - name: Start backend API
        env:
          DEFAULT_USER: ${{ secrets.DEFAULT_USER }}
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LOG_LEVEL: 2
          AWS_CONFIG_FILE: .aws/config
          PORT: 5000
          DEBUG: "False"
        run: |
          ./run api &
          echo "Waiting for API to start..."
          sleep 20

      # Pass env vars to web server + tests
      - name: Run Playwright tests
        working-directory: frontend
        env:
          DEFAULT_USER: ${{ secrets.DEFAULT_USER }}
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
          VITE_API_URL: "http://localhost:5000"
        run: npx playwright test --reporter=list


 

